### ISSUE TITLE
Это не рабочее решение

### ISSUE THREAD

**Issue by coursar** [Mavlon90/cashback#3]
https://github.com/Mavlon90/cashback/blob/af6193e1b436095b0503102a759efc41d6a95c4c/src/js/app.js#L25-L32

Останьтесь после лекции - разберём

**Comment by Mavlon90** [comment]
Извините пожалуйста, мне не очень понятно принцип работы Cashback объясните пожалуйста. #3

**Comment by Mavlon90** [comment]
Извините пожалуйста, мне не очень понятно принцип работы Cashback объясните пожалуйста. #3

**Comment by coursar** [comment]
Если сделали - issue нужно закрывать
